language: php

php:
  - 5.6
  - 7

matrix:
  fast_finish: true

sudo: false

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_script:
  - pecl install mongodb
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit
